name: ircminer
version: 1a
summary: A script to mine IRC logs for fun and profit, well really just entertainment.
description: |
 A script to mine IRC logs for fun and profit, well really just entertainment.
grade: stable 
confinement: strict
base: core18


apps:
  ircminer:
    command: bin/ircMiner.py 
    plugs: 
    - home 

parts:
  ircminer:
    plugin: python
    python-version: python3
    python-packages: 
    - numpy
    - WordCloud
    - plotly
    - matplotlib

  wrapper:
    plugin: dump
    source: files/
    
  mypackages:
    plugin: nil
    stage-packages:
    - python3 
    - python3-pil
    - python3-tk
    - libblas-dev
